export * from './admins.service';
import { AdminsService } from './admins.service';
export * from './appinstances.service';
import { AppinstancesService } from './appinstances.service';
export * from './applications.service';
import { ApplicationsService } from './applications.service';
export * from './channels.service';
import { ChannelsService } from './channels.service';
export * from './clients.service';
import { ClientsService } from './clients.service';
export * from './domains.service';
import { DomainsService } from './domains.service';
export * from './locales.service';
import { LocalesService } from './locales.service';
export * from './system.service';
import { SystemService } from './system.service';
export * from './users.service';
import { UsersService } from './users.service';
export const APIS = [AdminsService, AppinstancesService, ApplicationsService, ChannelsService, ClientsService, DomainsService, LocalesService, SystemService, UsersService];
