/**
 * Motif Platform Service API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2.0.0
 * Contact: info@vipera.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */import { SharedUserData } from './sharedUserData';
import { UserData } from './userData';
import { UserKey } from './userKey';


export interface User extends UserKey { 
    userIdInt?: string;
    msisdn?: string;
    serial?: string;
    locale?: string;
    state?: string;
    prevState?: string;
    email?: string;
    created?: Date;
    lastLogin?: Date;
}